name: CI

# Controls when the action will run.
# Triggers the workflow on push to master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        path: master
    
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Setup Python
      uses: actions/setup-python@v2

    # It's faster to reinstall from pip each time than to cache
    - name: Build site
      run: |
        rm -rf gh-pages/*
        pip install wheel
        pip install -U jupyter-book
        jupyter-book build master
        mv master/_build/html/* gh-pages
        
    - name: Git push
      uses: EndBug/add-and-commit@v4
      with:
        cwd: 'gh-pages'
        ref: 'gh-pages'
        message: 'new build'
        force: true
