# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    # Build
    - name: Build
      run: |
        git checkout build
        rm -rf ./*
        git add -A
        git commit -m "clear"
        git checkout master
        pip install -U jupyter-book
        jupyter-book build ./
        git checkout build
        mv _build/html/* .
        rm -rf _build
        git add -A
        git commit -m "new build"
        git push
